apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: rms
type: Opaque
stringData:
  POSTGRES_PASSWORD: "admin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rms-config
  namespace: rms
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update" # dev only; prod -> validate + Flyway
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"
  # DB url uses in-cluster service DNS
  SPRING_DATASOURCE_URL: "jdbc:postgresql://resource-postgres:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  # Kafka bootstrap address (in-cluster)
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
