-- Drop existing tables (in correct order to respect FK constraints)
DROP TABLE IF EXISTS resource_read_model;
DROP TABLE IF EXISTS raw_json;
DROP TABLE IF EXISTS resource_change;

-- Initial schema for resource consumer service
CREATE TABLE IF NOT EXISTS resource_read_model (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type         VARCHAR(50)  NOT NULL,
    country_code VARCHAR(2)   NOT NULL,
    lat          DOUBLE PRECISION NOT NULL,
    lng          DOUBLE PRECISION NOT NULL,
    version      BIGINT       NOT NULL DEFAULT 0
    );

-- Raw Kafka messages archive
-- Stores the exact JSON payload plus delivery metadata

CREATE TABLE IF NOT EXISTS raw_json (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic            VARCHAR(200)      NOT NULL,
    kafka_partition  INT               NOT NULL,
    kafka_offset     BIGINT            NOT NULL,
    message_key      VARCHAR(255),
    payload          JSONB             NOT NULL,
    headers          JSONB,
    event_time       TIMESTAMPTZ,
    received_at      TIMESTAMPTZ       NOT NULL DEFAULT now()
    );


CREATE TABLE resource_change (
     id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     resource_id   BIGINT       NOT NULL,
     version_from  BIGINT,
     version_to    BIGINT,
     diff          JSONB        NOT NULL,         -- normalized diff object
     prev_json     JSONB,                         -- optional: full previous snapshot
     curr_json     JSONB         NOT NULL,        -- full current snapshot
     reason        VARCHAR(40)   NOT NULL,        -- CREATED/UPDATED/DELETED
     received_at   TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Prevent duplicate ingestion of the same record
ALTER TABLE raw_json
    ADD CONSTRAINT uq_rawjson_topic_part_offset
        UNIQUE (topic, kafka_partition, kafka_offset);


CREATE INDEX IF NOT EXISTS idx_resource_read_model_country ON resource_read_model(country_code);
CREATE INDEX IF NOT EXISTS idx_resource_read_model_type    ON resource_read_model(type);

CREATE INDEX idx_resource_change_res ON resource_change(resource_id, received_at DESC);
CREATE INDEX idx_resource_change_gin ON resource_change USING GIN (diff);

CREATE INDEX IF NOT EXISTS idx_rawjson_topic_received ON raw_json (topic, received_at DESC);
CREATE INDEX IF NOT EXISTS idx_rawjson_payload_gin    ON raw_json USING GIN (payload);
CREATE INDEX IF NOT EXISTS idx_rawjson_key            ON raw_json (message_key);
