server:
  port: 8087

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: resource-consumer
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # optional tuning
      max-poll-records: 50
      properties:
        spring.json.trusted.packages: com.gatto.rms.contracts
        spring.json.value.default.type: com.gatto.rms.contracts.ResourceView
